import type { ClienteCatalogoHbi } from '@/types/hbi/cliente.types';

/** Catálogo quemado de clientes — sin base de datos. */
export const CATALOGO_CLIENTES: ClienteCatalogoHbi[] = [
  {
    id: 'cli-deu-001',
    tipo: 'DEUDOR',
    razonSocial: 'Concesionaria Metro Verde S.A.',
    nit: '900.123.456-7',
    pais: 'Colombia',
    sector: 'Infraestructura / transporte',
    contacto: 'Laura Muñoz',
    email: 'laura.munoz@metroverde.co',
  },
  {
    id: 'cli-deu-002',
    tipo: 'DEUDOR',
    razonSocial: 'Energía Andina S.A.',
    nit: '800.456.789-1',
    pais: 'Colombia',
    sector: 'Energía renovable',
    contacto: 'Andrés Mejía',
    email: 'andres.mejia@energiaandina.com',
  },
  {
    id: 'cli-deu-003',
    tipo: 'DEUDOR',
    razonSocial: 'Grupo Pacífico Holdings',
    nit: '860.111.222-3',
    pais: 'Colombia',
    sector: 'Retail / corporativo',
    contacto: 'Camila Restrepo',
    email: 'camila.restrepo@grupopacifico.com',
  },
  {
    id: 'cli-deu-004',
    tipo: 'DEUDOR',
    razonSocial: 'Consorcio Vial Ecuador C.A.',
    nit: 'EC-1790123456001',
    pais: 'Ecuador',
    sector: 'Infraestructura vial',
    contacto: 'Diego Salazar',
    email: 'd.salazar@consorciovial.ec',
  },
  {
    id: 'cli-deu-005',
    tipo: 'DEUDOR',
    razonSocial: 'Infraestructura Salud Colombia S.A.S.',
    nit: '901.555.888-0',
    pais: 'Colombia',
    sector: 'Salud / PPP',
    contacto: 'Patricia Gómez',
    email: 'p.gomez@saludinfra.co',
  },
  {
    id: 'cli-deu-006',
    tipo: 'DEUDOR',
    razonSocial: 'Agroindustrial del Valle S.A.',
    nit: '890.333.444-5',
    pais: 'Colombia',
    sector: 'Agroindustria',
    contacto: 'Felipe Torres',
    email: 'f.torres@agrovalle.com',
  },
  {
    id: 'cli-deu-007',
    tipo: 'DEUDOR',
    razonSocial: 'Solar Andes Generación S.A.',
    nit: '900.777.666-2',
    pais: 'Perú',
    sector: 'Energía solar',
    contacto: 'Mariana López',
    email: 'm.lopez@solarandes.pe',
  },
  {
    id: 'cli-deu-008',
    tipo: 'DEUDOR',
    razonSocial: 'Puerto Caribe Logística S.A.',
    nit: '830.999.111-4',
    pais: 'Colombia',
    sector: 'Logística portuaria',
    contacto: 'Jorge Herrera',
    email: 'j.herrera@puertocaribe.com',
  },
  {
    id: 'cli-acr-001',
    tipo: 'ACREEDOR',
    razonSocial: 'Banco Andino de Inversión',
    nit: '860.002.334-1',
    pais: 'Colombia',
    sector: 'Banca de inversión',
    contacto: 'Felipe Restrepo',
    email: 'f.restrepo@bancoandino.com',
  },
  {
    id: 'cli-acr-002',
    tipo: 'ACREEDOR',
    razonSocial: 'Fondo Latam Infra III',
    nit: '900.888.777-6',
    pais: 'Estados Unidos',
    sector: 'Fondo de infraestructura',
    contacto: 'Sarah Mitchell',
    email: 's.mitchell@lataminfra.com',
  },
  {
    id: 'cli-acr-003',
    tipo: 'ACREEDOR',
    razonSocial: 'Banco Continental Syndicated',
    nit: '800.555.444-3',
    pais: 'Colombia',
    sector: 'Banca comercial',
    contacto: 'Ricardo Peña',
    email: 'r.pena@bcontinental.com',
  },
  {
    id: 'cli-acr-004',
    tipo: 'ACREEDOR',
    razonSocial: 'Development Finance Corp.',
    nit: 'US-DFC-2024',
    pais: 'Estados Unidos',
    sector: 'DFI / multilateral',
    contacto: 'James Carter',
    email: 'j.carter@dfc.gov',
  },
  {
    id: 'cli-acr-005',
    tipo: 'ACREEDOR',
    razonSocial: 'Seguros del Pacífico S.A.',
    nit: '860.444.333-2',
    pais: 'Colombia',
    sector: 'Aseguradora / acreedor mezzanine',
    contacto: 'Ana Beltrán',
    email: 'a.beltran@segurospacifico.com',
  },
  {
    id: 'cli-acr-006',
    tipo: 'ACREEDOR',
    razonSocial: 'Helm Capital Partners',
    nit: '900.222.111-8',
    pais: 'Colombia',
    sector: 'Private credit',
    contacto: 'Roberto Vega',
    email: 'r.vega@helmcapital.com',
  },
  {
    id: 'cli-acr-007',
    tipo: 'ACREEDOR',
    razonSocial: 'Banco Internacional del Caribe',
    nit: '800.666.555-9',
    pais: 'Panamá',
    sector: 'Banca internacional',
    contacto: 'Carlos Mendoza',
    email: 'c.mendoza@bicaribe.com',
  },
  {
    id: 'cli-acr-008',
    tipo: 'ACREEDOR',
    razonSocial: 'Fondo Verde ESG Latam',
    nit: '900.333.222-1',
    pais: 'Chile',
    sector: 'Fondo ESG',
    contacto: 'Valentina Soto',
    email: 'v.soto@verdeesg.cl',
  },
];

export function listarDeudores(): ClienteCatalogoHbi[] {
  return CATALOGO_CLIENTES.filter((c) => c.tipo === 'DEUDOR');
}

export function listarAcreedores(): ClienteCatalogoHbi[] {
  return CATALOGO_CLIENTES.filter((c) => c.tipo === 'ACREEDOR');
}

export function buscarClientePorId(id: string): ClienteCatalogoHbi | undefined {
  return CATALOGO_CLIENTES.find((c) => c.id === id);
}
